name: Rust

on:
  push:
    branches: [ "vilios" ]
  pull_request:
    branches: [ "vilios" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies and build
      run: python3 ./tools/dev_container ./tools/install-deps && cargo build